Expansion.create!(name: 'Catan: Cities & Knights', price: 62.99 , description: "Adds several new aspects to Settlers of Catan but the two major ones are creating knights to protect the land from invading barbarians and building city improvements that confer benefits upon that city's owner. Adds tactical complexity to the game and game length.", status: 'None', stock_quantity: 5)

Expansion.create!(name: 'Catan: 5-6 Player Expansion', price: 31.99 , description: "Allows you to add up to two more opponents to The Settlers of Catan. The only change in the rules is that there is a building round at the end of each turn in which any player can build.", status: 'New', stock_quantity: 5)

Expansion.create!(name: 'Catan: Traders & Barbarians', price: 47.99 , description: "Traders & Barbarians is distributed as the third major expansion for The Settlers of Catan, although it is actually a compilation of small expansions and variants. (It is independent of the Seafarers and Cities & Knights expansions, but can be combined with them.)", status: 'None', stock_quantity: 2)

Expansion.create!(name: 'Catan: Explorers & Pirates', price: 62.99 , description: "Catan: Explorers & Pirates is the fourth major expansion for The Settlers of Catan (following Seafarers, Cities & Knights and Traders & Barbarians) and it includes five scenarios and three missions; some of the scenarios make use of the missions while others do not.

Catan: Explorers & Pirates differs from the Catan base game in three main ways. First, instead of having only a single island in the game on which players build and compete for resources, three islands are present – but the landscape of only one of these islands is known at the start of the game. Players start on this island, then build ships and bring settlers into play so that they can then travel to new lands. When a ship ends its movement on unexplored territory, that hex is revealed and a randomly-drawn number chip placed on it, with the player earning one resource as a reward – assuming the hex produces resources, that is. (The number of unknown tiles varies from 16 to 32, depending on the scenario.) A settler and ship can be transformed into a port settlement, from which roads and new ships can be built to enable further exploration.", status: 'None', stock_quantity: 9)

Expansion.create!(name: 'Pandemic: On the Brink', price: 49.99 , description: "Pandemic: On the Brink includes new event cards, new role cards, rules for five players, and optional game challenges to increase the difficulty of the Pandemic base game. These new challenges, which can be used individually or combined for even more difficult play, are as follows:

The Virulent Strain challenge makes one disease become particularly deadly in unpredictable ways.
The Mutation challenge adds a fifth (purple) disease that behaves differently than the original four.
The Bio-Terrorist challenge pits one player against the others!", status: 'None', stock_quantity: 13)

Expansion.create!(name: 'Pandemic: In the Lab', price: 39.99 , description: "In Pandemic: In the Lab, the second expansion for Pandemic, you will use a new game board that allows you to move the pawns in a laboratory. The goal of this activity is the same as in the base game – finding cures for diseases – but this time in a new way. Behind sealed bio-hazard doors, scientists race against time to sequence diseases, take samples, and test cures.

Pandemic: In the Lab includes four new roles, new Virulent Strain events, and a Worldwide Panic Mutation scenario. Players can compete individually or on rival teams (when playing with four or six players). Can your team work together in the lab to save humanity?

Pandemic: In the Lab requires both the base game and Pandemic: On the Brink to play.", status: 'New', stock_quantity: 7)

Expansion.create!(name: 'Pandemic: The Cure', price: 49.99 , description: "Pandemic: The Cure, a dice-based version of the popular Pandemic board game, sets up in less than a minute and plays in 30 minutes. As in the board game, four diseases threaten the world and it's up to your team to save humanity. You and your team must keep the world's hotspots in check before they break out of control, while researching cures to the four plagues.

Players roll dice each turn to determine the actions available to them. They can fly and sail between the six major population centers of the world, treat disease in their current region, collect samples for further study, and exchange knowledge to help them in their goal of discovering cures. Each player takes on a different role that has its own unique set of dice and abilities — and players must take advantage of their specializations if they are to have any hope of winning the game. The Dispatcher, for example, can spend dice to fly others around the board, while the Medic is particularly adept at treating disease. Players can roll their dice as often as they like, but the more times they re-roll for the perfect turn, the more likely the next epidemic will occur.

At the end of each turn, new 'infection dice' are rolled to determine the type and location of newly infected populations. If any region on the board is infected with more than three dice of a given color, an outbreak occurs, spreading disease into an adjacent region. If too many outbreaks take place, too many people get infected, or the rate of infection gets too high, all the players lose. If, however, the players can discover the cures to the four diseases, they all win and humanity is saved!", status: 'None', stock_quantity: 4)
